spring:
  datasource:
    url: jdbc:postgresql://10.10.11.252:5432/omni_core_db
    username: postgres
    password: Password@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 150
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      keepalive-time: 30000
      leak-detection-threshold: 60000

  data:
    redis:
      host: 10.10.11.252
      port: 6379
      database: 2
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      authentication:
        baseConfig: default
        failureRateThreshold: 60
        slidingWindowSize: 20
      BBPS-fetchBill:
        baseConfig: default
        waitDurationInOpenState: 10s
      ISO8583-purchase:
        baseConfig: default
        failureRateThreshold: 40
        slidingWindowSize : 20

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000ms
        exponentialBackoffMultiplier: 2
        enableExponentialBackoff: true
    instances:
      authentication:
        baseConfig: default
        maxAttempts: 2
        waitDuration: 500ms
      BBPS-fetchBill:
        baseConfig: default
        maxAttempts: 2
      ISO8583-purchase:
        baseConfig: default
        maxAttempts: 1

  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
        cancelRunningFuture: true
    instances:
      authentication:
        timeoutDuration: 2s
      BBPS-fetchBill:
        timeoutDuration: 3s
      ISO8583-purchase:
        timeoutDuration: 5s

# Channel specific configurations
channels:
  BBPS:
    timeout: 3000
    maxRetries: 2
    circuitBreaker: true
    batchSize: 100
  ISO8583:
    timeout: 5000
    maxRetries: 1
    circuitBreaker: true
    batchSize: 50
  UPI:
    timeout: 6000
    maxRetries: 2
    circuitBreaker: true
    batchSize: 200

# Authentication Configuration
auth:
  jwt:
    secret: ${JWT_SECRET:my-very-secure-jwt-secret-key-that-should-be-at-least-256-bits}
    expirationMs: 3600000 # 1 hour
  lockout:
    maxFailedAttempts: 3
    lockoutDurationMinutes: 15
  cache:
    ttl: 300 # 5 minutes

# Logging Configuration
logging:
  level:
    com.concerto.omnichannel: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] [%X{channel}] %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom application properties
app:
  transaction:
    defaultTimeout: 30000
    maxConcurrentTransactions: 1000
  security:
    encryption:
      algorithm: AES/GCM/NoPadding
      keyLength: 256
  monitoring:
    enabled: true
    alertThreshold: 95

# ISO8583 Configuration
iso8583:
  enabled: true
  packager:
    type: ascii
    ascii:
      config: iso87ascii.xml
    binary:
      config: iso87binary.xml
  tpdu:
    enabled: true
    identifier: "0x60"
    source: "0x0526"     # Source address
    destination: "0x00F1" # Destination address

# External Switch Configuration
switch:
  default:
    host: 10.10.10.166
    port: 1276
  connection:
    timeout: 5000
  read:
    timeout: 30000

# Connector Configuration
connector:
  timeouts:
    ISO8583: 5000
    BBPS: 3000
    UPI: 6000
    PG: 8000
    default: 10000

server:
  tomcat:
    threads:
      max: 300
      min-spare: 100
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 200