version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  payment-orchestrator:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=10.10.11.252  # Use actual IP since you're not using Docker Redis
      - REDIS_PORT=6379
      - DB_HOST=10.10.11.252
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health/redis/quick"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data: